
server:
  port: 10002
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/reasonable
    username: hongseok
    password: hongseok

allow-origin: http://localhost:3000

cloud:
  aws:
    credentials:
      accessKey: AKIA4REP2VDLTURRIO55
      secretKey: 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
    s3:
      bucket: reasonable-photo
    region:
      static: ap-northeast-2
    stack:
      auto: false